### PR TITLE
Removed pycurl and clean code

### PR DESCRIPTION
**Pull request by pawan2411**

### CODE REVIEW

**Comment by siznax** [comment]
Haha, thanks @pawan2411 !

**Comment by pawan2411** [comment]
@siznax when can we expect a release with removed pycurl?

**Comment by pawan2411** [comment]
@siznax can you please release current code version (one without pycurl)....

**Comment by siznax** [comment]
@pawan2411 I should be able to make a release this week

**Comment by andreasneo** [comment]
you can do `pip install git+https://github.com/siznax/wptools.git#egg=wptools` until released

**Pull request merged**
